#!/bin/bash

usage () {
    echo br FILENAME [OPTIONS]
    exit 1
}

if [[ $# -lt 1 ]]; then
    usage
fi

programname=$(basename $1)
programname=${programname%%.*}

if ! programpath=$(mktemp "/tmp/$programname.XXX"); then
    echo "Failed to create temporaryy file!"
    exit 1
fi

clang++ -std=c++14 $1 -o $programpath
shift
$programpath $@

trap "rm $programpath" EXIT
