#!/bin/bash
set -euo pipefail

ffmpeg_pid=$(pgrep ffmpeg | grep -v grep | awk '{print $2}')

if [ "$ffmpeg_pid" == "" ]; then
  echo "Cannot find an ffmpeg pid!"
  exit 255
fi

echo "Caffeinating while pid $ffmpeg_pid runs..."
caffeinate -imsw "$ffmpeg_pid"
