#!/bin/zsh

export CC=clang
export CFLAGS="--target=aarch64-unknown-linux-gnu \
--sysroot=/Volumes/CrossCompile/aarch64-linux-gnu/sysroot"

cargo nextest archive \
	--target=aarch64-unknown-linux-gnu \
	--archive-file=target/aarch64-unknown-linux-gnu/test.tar.zst
	
docker run -it --rm \
	-v "$PWD/target/aarch64-unknown-linux-gnu/test.tar.zst:/tmp/test.tar.zst" \
	-v "$PWD:/app" \
	-t docker-test \
	"$@"
