#!/bin/bash

docker run \
  --mount type=bind,source="$PWD",target=/app,readonly \
  --mount type=bind,source=/Library/Apple/usr/libexec/oah/RosettaLinux,target=/mnt/rosetta,readonly \
  --rm -t docker-run \
  /app/"$1" "${@:2}"
