#!/bin/bash

TARGET=$(pwd -P)
APP="$TARGET/$1"

if [[ "$1" = /* ]]; then
  APP=$1
fi

docker run \
  --mount type=bind,source="$TARGET",target="$TARGET",readonly \
  --rm -t docker-run \
  "$APP" "${@:2}"
