#!/bin/bash
excutables=( pip pip2 pip3 )
for exec in ${excutables[@]}; do
    if which -s $exec; then
        $exec list --outdated --format=freeze | cut -d= -f1 |
        sudo -H xargs $exec install -U
    fi
done
