#!/bin/bash
set -euo pipefail

vspipe ~/Movies/nijigasaki.vpy -c y4m - | \
ffmpeg -i pipe: \
    -i /tmp/input.mov \
    -map 0:v:0 -c:v libx264 -preset placebo -level 5.2 \
    -x264opts crf=16:me=umh:rc-lookahead=256:deblock="-2,-2":qcomp=0.7:aq-mode=3:aq-strength=0.6:merange=32:psy-rd=0.6,0:no-dct-decimate \
    -map 1:a:0 -c:a copy \
    output.mov
