#!/bin/bash
usage() {
    echo "Usage: runSuite suitefile program" >&2
    exit 1
}

if [ ${#} -ne 2 ]; then
    usage
fi

IFS=$' \t\n' tests=($(cat $1))
suitepath=$(dirname $1)
program=$(basename $2)
programpath=$2

if ! tmpdir=$(mktemp -qd "/tmp/$program.XXX"); then
    echo "Cannot create temporary folder!" >&2
    exit 1
fi

trap "rm -r $tmpdir" EXIT

for test in ${tests[@]}; do
    if [[ $test =~ ^#.* ]]; then
        continue
    fi

    if ! tmpfile=$(mktemp -q "$tmpdir/$test.out.XXX"); then
        echo "Cannot create temporary out file!" >&2
        exit 1
    fi

    if ! tmperr=$(mktemp -q "$tmpdir/$test.err.XXX"); then
        echo "Cannot create temporary err file!" >&2
        exit 1
    fi

    if ! [ -f "$suitepath/$test.in" ]; then
        echo "File $test.in is missing." >&2
        exit 1
    fi
    if ! [ -f "$suitepath/$test.out" ]; then
        echo "File $test.out is missing." >&2
        exit 1
    fi

    if [ -f "$suitepath/$test.args" ]; then
        IFS=$' \t\n' args=($(cat $suitepath/$test.args))
    else
        args=()
    fi

    if ! [ $(command -v $programpath) ]; then
        programpath=./$2
    fi

    $programpath ${args[@]} <$suitepath/$test.in >$tmpfile 2>$tmperr

    if [ $? -ne 0 ]; then
        echo "Error:"
        echo "$(cat $tmpfile)"
        echo "$(cat $tmperr)"
        exit 1
    fi

    if ! diff -q $suitepath/$test.out $tmpfile &> /dev/null; then
        echo "Test failed: $test"
        echo "Input:"
        echo "$(cat $suitepath/$test.in)"

        echo "Expected:"
        echo "$(cat -A $suitepath/$test.out)"

        echo "Actual:"
        echo "$(cat -A $tmpfile)"
    fi
done
