#!/usr/bin/env bash
set -e

server_address=$1
shift

rsync -e "ssh $*" -az $HOME/.ssh/id_server $server_address:.ssh/
ssh $server_address $@ -t 'chmod 400 $HOME/.ssh/id_server && \
    echo -e "Host github.com\n\tStrictHostKeyChecking no\n\tIdentityFile $HOME/.ssh/id_server" > ~/.ssh/config && \
    rm -rf .dotfiles && \
    git clone git@github.com:inflation/dotfiles.git -b ml .dotfiles && \
    cd .dotfiles && bash startup.sh'
gpg --export-secret-key 0C3A1E0B | ssh $server_address $@ gpg2 --import --batch
sst $server_address $@
