#!/usr/bin/env bash
set -e

server_address=$1
shift

ssh $server_address $@ -A -t 'rm -rf .dotfiles && \
    git clone git@github.com:inflation/dotfiles.git -b server .dotfiles && \
    cd .dotfiles && bash startup.sh'
gpg --export-secret-key 0C3A1E0B | ssh $server_address $@ gpg2 --import --batch
sst $server_address $@
