#! /bin/bash

duration=$(ffprobe -i "$1" -select_streams v:0 -show_entries stream=duration -v quiet -of csv | cut -f2 -d, | cut -f1 -d.)
destination=$(mktemp -d)

for i in {1..15}; do
    time=$((i * duration / 16))
    ffmpeg -ss $time -skip_frame nokey -i "$1" -vsync 0 -vframes 1 -vf scale=iw/2:ih/2 -c:v mjpeg -v quiet $destination/thumb_$i.jpg
done

montage $destination/*.jpg -geometry +2+2 thumbs.jpg
rm -r $destination
